### ISSUE TITLE
Respect Windows output device selection

### ISSUE THREAD

**Issue by JasonWei512** [RustAudio/rodio#463]
I am using rodio to play audio. When I change the output device on Windows, the audio continues to play on the old device.
There is a similar issue for macOS (https://github.com/RustAudio/rodio/issues/327). But that is fixed in https://github.com/RustAudio/cpal/pull/648.
![image](https://user-images.githubusercontent.com/16899918/210552406-e66c4769-4b0d-4a2b-ac38-fa4fba0e6d5d.png)
![image](https://user-images.githubusercontent.com/16899918/210552478-88b2212f-f0fd-41c1-93a9-d8e383c7271a.png)

**Comment by dvdsk** [comment]
Thanks for adding the issue upstream btw! I'll keep this issue open to keep track of it.

**Comment by philpax** [comment]
I've PR'd https://github.com/RustAudio/cpal/pull/1027, which is an updated version of https://github.com/RustAudio/cpal/pull/754. This is not a complete fix, as it will only work on >=Windows 8, but it should be sufficient to unblock most use cases.

To use it with `rodio`, first depend on a version of `rodio` that's compatible with `cpal`'s HEAD; I've prepared [a fork/PR for this](https://github.com/RustAudio/rodio/pull/803). Once you've done this, patch `cpal` in your dependency tree to use my PR's version:

```toml
[dependencies]
rodio = { git = "https://github.com/philpax/rodio.git", branch = "latest-cpal-fixes" }

[patch.'https://github.com/RustAudio/cpal']
cpal = { git = "https://github.com/philpax/cpal.git", branch = "audio-device-fix-updated" }
```

(I wanted to restrict it to just a `cpal` patch, but there was a minor change in the `cpal` API surface that required changes in `rodio`. My `rodio` fork will not be necessary once they sync up again.)

After you make any necessary API fixes for `rodio` (I didn't have to make any), you should now be able to change your default device around to your heart's content. For example, here's the changes I made for [my music player](https://github.com/philpax/blackbird/commit/22dd03c9c93438826b5cf24168cfe2837a73453a).
